import { signal } from '@angular/core';

export function createMockWellStore() {
  return {
    wellNames: signal([]),
    selectedEpANum: signal(null),
    selectedDate: signal(new Date()),
    wellDetails: signal(null),
    loading: signal(false),
    error: signal(null),
    animationTrigger: signal(0),
    wellNamesPage: signal(0),
    uniqueWellNames: signal([]),
    totalPages: signal(0),
    pagedWellNames: signal([]),
    hasPrevPage: signal(false),
    hasNextPage: signal(false),
    isLoaded: signal(false),
    isInitialLoading: signal(false),
    isDetailsLoading: signal(false),
    totalDepth: signal(0),
    diagramData: signal(null),
    miscWellData: signal(null),
    pickedFormations: signal([]),
    offsetWells: signal([]),
    wellsLogsIndicators: signal(null),
    wellTestResults: signal([]),
    wellHeaderData: signal(null),
    databaseInfo: signal(null),
    operationSummary: signal(null),
    formationInfo: signal(null),
    casingInfo: signal(null),
    wwellTest: signal(null),
    selectWell: jest.fn(),
    loadWellNames: jest.fn(),
    setSelectedDate: jest.fn(),
    getFormattedDate: jest.fn().mockReturnValue(''),
    nextPage: jest.fn(),
    prevPage: jest.fn(),
  };
}
