export {
    selectWellNamesFromList,
    selectTotalPages,
    selectPagedWellNames,
    selectPageIndexForEpANum,
    selectHasPrevPage,
    selectHasNextPage,
    selectWellEpANum,
    selectTotalDepth,
    selectDiagramData,
    selectMiscWellData,
    selectPickedFormations,
    selectOffsetWells,
    selectWellLogsIndicators,
    selectWellTestResults,
    selectWellHeaderViewModel,
    selectDatabaseInfoViewModel,
    selectOperationSummaryViewModel,
    selectFormationInfoViewModel,
    selectCasingInfoViewModel,
    selectWwellTestViewModel,
    selectWaterWellTestResultsFromData,
} from 'src/app/core/store/shared/well-data.selectors';
